package com.alexpauv.pokemon.exception;

public enum ErrorCode {
    INTERNAL_ERROR,
    BAD_CREDENTIALS,
    ACCOUNT_LOCKED,
    ACCOUNT_DEAD,
    PASSWORD_RESET_EMAIL_SENDING_FAILURE,
    INVALID_PASSWORD_RESET_TOKEN,
    WEAK_PASSWORD,
    USERNAME_ALREADY_EXISTS,
    USERNAME_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    EMAIL_NOT_FOUND,
    ROLE_NOT_FOUND,
}
